# Generated by Django 2.2.5 on 2019-11-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191025_1530'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='room',
            field=models.ManyToManyField(blank=True, to='rooms.Room'),
        ),
    ]
